# coding: utf-8

"""
    设备上报日志记录查询

    查询设备上报日志。

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.log_manager_service_northbound_api import LogManagerServiceNorthboundApi


class TestLogManagerServiceNorthboundApi(unittest.TestCase):
    """ LogManagerServiceNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.log_manager_service_northbound_api.LogManagerServiceNorthboundApi()

    def tearDown(self):
        pass

    def test_query_log_data(self):
        """
        Test case for query_log_data

        查询设备上报日志记录
        """
        pass


if __name__ == '__main__':
    unittest.main()
