# coding: utf-8

"""
    AP站点模板SSID配置

    AP站点模板SSID第三方接口说明。 

    OpenAPI spec version: 1.5.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.site_template_apssid_netcfg_northbound_api import SiteTemplateApssidNetcfgNorthboundApi


class TestSiteTemplateApssidNetcfgNorthboundApi(unittest.TestCase):
    """ SiteTemplateApssidNetcfgNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.site_template_apssid_netcfg_northbound_api.SiteTemplateApssidNetcfgNorthboundApi()

    def tearDown(self):
        pass

    def test_create_site_template_ssid_config(self):
        """
        Test case for create_site_template_ssid_config

        新增该站点模板的SSID配置
        """
        pass

    def test_delete_site_template_ssid_config(self):
        """
        Test case for delete_site_template_ssid_config

        删除该站点模板的SSID配置
        """
        pass

    def test_get_site_template_ssid_config(self):
        """
        Test case for get_site_template_ssid_config

        查询该站点模板的SSID配置
        """
        pass

    def test_update_site_template_ssid_config(self):
        """
        Test case for update_site_template_ssid_config

        修改该站点模板的SSID配置
        """
        pass


if __name__ == '__main__':
    unittest.main()
