# coding: utf-8

"""
    站点内设备域名配置

    站点内设备域名配置北向接口，主要特性： · 查询站点内设备域名配置 · 修改站点内设备域名配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.domain_name_dto import DomainNameDto


class TestDomainNameDto(unittest.TestCase):
    """ DomainNameDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainNameDto(self):
        """
        Test DomainNameDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.domain_name_dto.DomainNameDto()
        pass


if __name__ == '__main__':
    unittest.main()
