# coding: utf-8

"""
    站点模板SNMP配置

    站点模板SNMP配置第三方接口说明。 

    OpenAPI spec version: 1.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.target_hosts_dto import TargetHostsDto


class TestTargetHostsDto(unittest.TestCase):
    """ TargetHostsDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTargetHostsDto(self):
        """
        Test TargetHostsDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.target_hosts_dto.TargetHostsDto()
        pass


if __name__ == '__main__':
    unittest.main()
