# coding: utf-8

"""
    PoE电源状态查询

    查询设备PoE电源状态。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.poe_power_state_data import PoePowerStateData


class TestPoePowerStateData(unittest.TestCase):
    """ PoePowerStateData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPoePowerStateData(self):
        """
        Test PoePowerStateData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.poe_power_state_data.PoePowerStateData()
        pass


if __name__ == '__main__':
    unittest.main()
