# coding: utf-8

"""
    交换机端口配置

    LSW端口配置北向接口，主要特性： · 查询交换机所有接口信息 · 修改交换机以太接口配置 · 创建交换机Eth-Trunk接口 · 修改交换机Eth-Trunk接口 · 删除交换机Eth-Trunk接口 

    OpenAPI spec version: 1.4.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.lsw_port_northbound_api import LSWPortNorthboundApi


class TestLSWPortNorthboundApi(unittest.TestCase):
    """ LSWPortNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.lsw_port_northbound_api.LSWPortNorthboundApi()

    def tearDown(self):
        pass

    def test_config(self):
        """
        Test case for config

        修改交换机端口配置
        """
        pass

    def test_create_eth_trunk(self):
        """
        Test case for create_eth_trunk

        创建交换机EthTrunk端口
        """
        pass

    def test_delete_eth_trunk(self):
        """
        Test case for delete_eth_trunk

        删除交换机EthTrunk端口
        """
        pass

    def test_get_config(self):
        """
        Test case for get_config

        查询交换机端口配置
        """
        pass

    def test_update_eth_trunk(self):
        """
        Test case for update_eth_trunk

        修改交换机EthTrunk端口
        """
        pass


if __name__ == '__main__':
    unittest.main()
