# coding: utf-8

"""
    终端用户列表信息查询

    · 站点维度终端用户列表查询 · 站点维度TopN终端流量数据查询 · 设备维度下终端用户信息查询 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.station_open_api_api import StationOpenApiApi


class TestStationOpenApiApi(unittest.TestCase):
    """ StationOpenApiApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.station_open_api_api.StationOpenApiApi()

    def tearDown(self):
        pass

    def test_query_device_station_info(self):
        """
        Test case for query_device_station_info

        查询设备维度下终端用户信息
        """
        pass

    def test_query_site_station_info(self):
        """
        Test case for query_site_station_info

        查询站点维度下终端用户信息
        """
        pass

    def test_query_traffic_statistic_info(self):
        """
        Test case for query_traffic_statistic_info

        查询站点维度下TopN终端流量数据
        """
        pass


if __name__ == '__main__':
    unittest.main()
