# coding: utf-8

"""
    mac帐号管理

    mac帐号管理

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ids import Ids


class TestIds(unittest.TestCase):
    """ Ids unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIds(self):
        """
        Test Ids
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ids.Ids()
        pass


if __name__ == '__main__':
    unittest.main()
