# coding: utf-8

"""
    设备BootROM密码配置

    设备BootROM密码配置第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.boot_rom_response import BootRomResponse


class TestBootRomResponse(unittest.TestCase):
    """ BootRomResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBootRomResponse(self):
        """
        Test BootRomResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.boot_rom_response.BootRomResponse()
        pass


if __name__ == '__main__':
    unittest.main()
