# coding: utf-8

"""
    设备基础性能数据信息查询

    · 查询设备网络速率历史数据 · 查询站点维度TopN设备或者全部设备的上行流量、下行流量 · 查询站点维度设备连接终端数历史数据 · 查询单设备连接终端数历史数据 · 查询租户维度下设备状态历史数据 · 查询基于站点的站点健康度和设备健康度 · 查询站点下TOP N SSID流量和最近在线用户数 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.performance_open_api_api import PerformanceOpenApiApi


class TestPerformanceOpenApiApi(unittest.TestCase):
    """ PerformanceOpenApiApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.performance_open_api_api.PerformanceOpenApiApi()

    def tearDown(self):
        pass

    def test_query_device_count_trend(self):
        """
        Test case for query_device_count_trend

        查询租户维度下设备状态历史数据列表
        """
        pass

    def test_query_device_station_statistic(self):
        """
        Test case for query_device_station_statistic

        查询设备连接终端数历史数据
        """
        pass

    def test_query_device_traffic(self):
        """
        Test case for query_device_traffic

        查询站点维度TopN设备或者全部设备的上行流量、下行流量
        """
        pass

    def test_query_network_traffic(self):
        """
        Test case for query_network_traffic

        查询设备网络速率历史数据
        """
        pass

    def test_query_site_health_list(self):
        """
        Test case for query_site_health_list

        基于站点的站点健康度查询
        """
        pass

    def test_query_site_station_statistic(self):
        """
        Test case for query_site_station_statistic

        查询站点维度设备连接终端数历史数据
        """
        pass

    def test_query_top_nssid_traffic(self):
        """
        Test case for query_top_nssid_traffic

        查询TOP N SSID流量和最近在线用户数
        """
        pass

    def test_single_device_performance_detail(self):
        """
        Test case for single_device_performance_detail

        查询单设备的性能数据
        """
        pass


if __name__ == '__main__':
    unittest.main()
