# coding: utf-8

"""
    防火墙设备NAT配置

    防火墙设备NAT配置第三方接口。

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.fw_nat_delete_response_dto import FwNatDeleteResponseDto


class TestFwNatDeleteResponseDto(unittest.TestCase):
    """ FwNatDeleteResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFwNatDeleteResponseDto(self):
        """
        Test FwNatDeleteResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.fw_nat_delete_response_dto.FwNatDeleteResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
