# coding: utf-8

"""
    射频管理国家码查询

    射频管理国家码第三方北向接口。     

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.radio_country_channel_dto import RadioCountryChannelDto


class TestRadioCountryChannelDto(unittest.TestCase):
    """ RadioCountryChannelDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRadioCountryChannelDto(self):
        """
        Test RadioCountryChannelDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.radio_country_channel_dto.RadioCountryChannelDto()
        pass


if __name__ == '__main__':
    unittest.main()
