# coding: utf-8

"""
    用户管理

    用户管理第三方北向接口。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.user_mgr_third_api import UserMgrThirdApi


class TestUserMgrThirdApi(unittest.TestCase):
    """ UserMgrThirdApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.user_mgr_third_api.UserMgrThirdApi()

    def tearDown(self):
        pass

    def test_add_user_third(self):
        """
        Test case for add_user_third

        新增用户信息
        """
        pass

    def test_delete_user_third(self):
        """
        Test case for delete_user_third

        删除指定用户
        """
        pass

    def test_get_user_third(self):
        """
        Test case for get_user_third

        查询内置用户信息
        """
        pass

    def test_update_user_third(self):
        """
        Test case for update_user_third

        修改用户信息
        """
        pass


if __name__ == '__main__':
    unittest.main()
