# coding: utf-8

"""
    终端用户列表信息查询

    · 站点维度终端用户列表查询 · 站点维度TopN终端流量数据查询 · 设备维度下终端用户信息查询 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.traffic_statistic_info import TrafficStatisticInfo


class TestTrafficStatisticInfo(unittest.TestCase):
    """ TrafficStatisticInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrafficStatisticInfo(self):
        """
        Test TrafficStatisticInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.traffic_statistic_info.TrafficStatisticInfo()
        pass


if __name__ == '__main__':
    unittest.main()
