# coding: utf-8

"""
    防火墙ASPF配置

    防火墙配置ASPF第三方接口，主要特性： · 查询ASPF配置 · 修改ASPF配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.aspf_config_dto import AspfConfigDto


class TestAspfConfigDto(unittest.TestCase):
    """ AspfConfigDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAspfConfigDto(self):
        """
        Test AspfConfigDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.aspf_config_dto.AspfConfigDto()
        pass


if __name__ == '__main__':
    unittest.main()
