# coding: utf-8

"""
    AP设备射频配置

    AP设备射频配置第三方接口说明。 

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ap_device_radio_api_dto import ApDeviceRadioApiDto


class TestApDeviceRadioApiDto(unittest.TestCase):
    """ ApDeviceRadioApiDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApDeviceRadioApiDto(self):
        """
        Test ApDeviceRadioApiDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ap_device_radio_api_dto.ApDeviceRadioApiDto()
        pass


if __name__ == '__main__':
    unittest.main()
