# coding: utf-8

"""
    失败重下发配置

    失败重下发

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.config_deploy_api_northbound_api import ConfigDeployApiNorthboundApi


class TestConfigDeployApiNorthboundApi(unittest.TestCase):
    """ ConfigDeployApiNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.config_deploy_api_northbound_api.ConfigDeployApiNorthboundApi()

    def tearDown(self):
        pass

    def test_deploy_all_config(self):
        """
        Test case for deploy_all_config

        全量下发配置
        """
        pass

    def test_redeploy_fail_config(self):
        """
        Test case for redeploy_fail_config

        重下发失败配置
        """
        pass


if __name__ == '__main__':
    unittest.main()
