# coding: utf-8

"""
    AP页面推送策略

    AP页面推送策略开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.entry_of_id2_name import EntryOfId2Name


class TestEntryOfId2Name(unittest.TestCase):
    """ EntryOfId2Name unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntryOfId2Name(self):
        """
        Test EntryOfId2Name
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.entry_of_id2_name.EntryOfId2Name()
        pass


if __name__ == '__main__':
    unittest.main()
