# coding: utf-8

"""
    配置保存

    配置保存接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.config_save_item import ConfigSaveItem


class TestConfigSaveItem(unittest.TestCase):
    """ ConfigSaveItem unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigSaveItem(self):
        """
        Test ConfigSaveItem
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.config_save_item.ConfigSaveItem()
        pass


if __name__ == '__main__':
    unittest.main()
