# coding: utf-8

"""
    交换机有线认证模板配置

    交换机有线认证模板，主要包括： · 创建站点下交换机有线认证模板配置 · 查询站点下交换机有线认证模板配置 · 修改站点下交换机有线认证模板配置 · 删除站点下交换机有线认证模板配置 · 修改站点交换机有线认证部分模板配置 · 增量绑站点交换机有线认证模板配置定 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.lsw_device_info import LswDeviceInfo


class TestLswDeviceInfo(unittest.TestCase):
    """ LswDeviceInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLswDeviceInfo(self):
        """
        Test LswDeviceInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.lsw_device_info.LswDeviceInfo()
        pass


if __name__ == '__main__':
    unittest.main()
