# coding: utf-8

"""
    用户流量信息查询

    控制器支持查询指定时间内流量和时长发生变化的用户流量信息分页查询北向接口。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.time_flow_st_infos_output_dto import TimeFlowStInfosOutputDto


class TestTimeFlowStInfosOutputDto(unittest.TestCase):
    """ TimeFlowStInfosOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeFlowStInfosOutputDto(self):
        """
        Test TimeFlowStInfosOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.time_flow_st_infos_output_dto.TimeFlowStInfosOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
