# coding: utf-8

"""
    设备上报日志记录查询

    查询设备上报日志。

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.query_response import QueryResponse


class TestQueryResponse(unittest.TestCase):
    """ QueryResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryResponse(self):
        """
        Test QueryResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.query_response.QueryResponse()
        pass


if __name__ == '__main__':
    unittest.main()
