# coding: utf-8

"""
    SSH客户端首次认证免公钥配置

    SSH客户端首次认证免公钥配置北向接口，主要特性： · 查询SSH客户端首次认证免公钥配置 · 修改SSH客户端首次认证免公钥配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.ssh_first_enable_northbound_api import SSHFirstEnableNorthboundApi


class TestSSHFirstEnableNorthboundApi(unittest.TestCase):
    """ SSHFirstEnableNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.ssh_first_enable_northbound_api.SSHFirstEnableNorthboundApi()

    def tearDown(self):
        pass

    def test_get_ssh_first_enable_config(self):
        """
        Test case for get_ssh_first_enable_config

        查询SSH客户端首次认证免公钥配置
        """
        pass

    def test_update_ssh_first_enable_config(self):
        """
        Test case for update_ssh_first_enable_config

        修改SSH客户端首次认证免公钥配置
        """
        pass


if __name__ == '__main__':
    unittest.main()
