# coding: utf-8

"""
    设备升级

    · 查询设备文件 · 创建站点升级 · 查询站点升级 · 查询设备升级 · 取消设备升级 · 删除站点升级 · 重新升级设备 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.upgrade_open_api_api import UpgradeOpenApiApi


class TestUpgradeOpenApiApi(unittest.TestCase):
    """ UpgradeOpenApiApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.upgrade_open_api_api.UpgradeOpenApiApi()

    def tearDown(self):
        pass

    def test_cancel_policy(self):
        """
        Test case for cancel_policy

        取消设备升级
        """
        pass

    def test_cancel_site_policy(self):
        """
        Test case for cancel_site_policy

        删除站点升级
        """
        pass

    def test_policy_configuration(self):
        """
        Test case for policy_configuration

        创建站点升级
        """
        pass

    def test_query_policy(self):
        """
        Test case for query_policy

        查询站点升级
        """
        pass

    def test_query_policy_detail(self):
        """
        Test case for query_policy_detail

        查询设备升级
        """
        pass

    def test_query_version(self):
        """
        Test case for query_version

        查询设备文件
        """
        pass

    def test_re_upgrade(self):
        """
        Test case for re_upgrade

        重新升级设备
        """
        pass


if __name__ == '__main__':
    unittest.main()
