# coding: utf-8

"""
    终端用户认证授权

    终端用户认证开放API 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.user_logout_input_dto import UserLogoutInputDto


class TestUserLogoutInputDto(unittest.TestCase):
    """ UserLogoutInputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserLogoutInputDto(self):
        """
        Test UserLogoutInputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.user_logout_input_dto.UserLogoutInputDto()
        pass


if __name__ == '__main__':
    unittest.main()
