# coding: utf-8

"""
    RADIUS模板管理

    RADIUS模板配置第三方北向接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.radius_template_northbound_api import RadiusTemplateNorthboundApi


class TestRadiusTemplateNorthboundApi(unittest.TestCase):
    """ RadiusTemplateNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.radius_template_northbound_api.RadiusTemplateNorthboundApi()

    def tearDown(self):
        pass

    def test_create_radius_template(self):
        """
        Test case for create_radius_template

        创建RADIUS模板
        """
        pass

    def test_delete_radius_template(self):
        """
        Test case for delete_radius_template

        删除RADIUS模板
        """
        pass

    def test_get_radius_template(self):
        """
        Test case for get_radius_template

        查询RADIUS模板
        """
        pass

    def test_update_radius_template(self):
        """
        Test case for update_radius_template

        修改RADIUS模板
        """
        pass


if __name__ == '__main__':
    unittest.main()
