# coding: utf-8

"""
    本地用户配置管理

    本地用户配置北向接口，主要特性： · 查询本地用户配置 · 修改本地用户配置 · 创建本地用户配置 

    OpenAPI spec version: 1.2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.local_user_security_info_dto import LocalUserSecurityInfoDto


class TestLocalUserSecurityInfoDto(unittest.TestCase):
    """ LocalUserSecurityInfoDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocalUserSecurityInfoDto(self):
        """
        Test LocalUserSecurityInfoDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.local_user_security_info_dto.LocalUserSecurityInfoDto()
        pass


if __name__ == '__main__':
    unittest.main()
