# coding: utf-8

"""
    单板管理

    单板管理第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.board_delete_dto import BoardDeleteDto


class TestBoardDeleteDto(unittest.TestCase):
    """ BoardDeleteDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBoardDeleteDto(self):
        """
        Test BoardDeleteDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.board_delete_dto.BoardDeleteDto()
        pass


if __name__ == '__main__':
    unittest.main()
