# coding: utf-8

"""
    AP DHCP配置

    AP DHCP配置第三方接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.tenancy_config_api_dto import TenancyConfigApiDto


class TestTenancyConfigApiDto(unittest.TestCase):
    """ TenancyConfigApiDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTenancyConfigApiDto(self):
        """
        Test TenancyConfigApiDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.tenancy_config_api_dto.TenancyConfigApiDto()
        pass


if __name__ == '__main__':
    unittest.main()
