# coding: utf-8

"""
    AP页面推送策略

    AP页面推送策略开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.add_portal_page_rule_input_dto import AddPortalPageRuleInputDto


class TestAddPortalPageRuleInputDto(unittest.TestCase):
    """ AddPortalPageRuleInputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddPortalPageRuleInputDto(self):
        """
        Test AddPortalPageRuleInputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.add_portal_page_rule_input_dto.AddPortalPageRuleInputDto()
        pass


if __name__ == '__main__':
    unittest.main()
