# coding: utf-8

"""
    终端应用流量信息查询

    终端TopN应用流量查询。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.application_info_resp import ApplicationInfoResp


class TestApplicationInfoResp(unittest.TestCase):
    """ ApplicationInfoResp unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationInfoResp(self):
        """
        Test ApplicationInfoResp
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.application_info_resp.ApplicationInfoResp()
        pass


if __name__ == '__main__':
    unittest.main()
