# coding: utf-8

"""
    认证模板管理

    认证模板北向接口定义 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.authen_profile_delete_resp_dto import AuthenProfileDeleteRespDto


class TestAuthenProfileDeleteRespDto(unittest.TestCase):
    """ AuthenProfileDeleteRespDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenProfileDeleteRespDto(self):
        """
        Test AuthenProfileDeleteRespDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.authen_profile_delete_resp_dto.AuthenProfileDeleteRespDto()
        pass


if __name__ == '__main__':
    unittest.main()
