# coding: utf-8

"""
    交换机管理VLAN配置

    LSW管理VLAN配置北向接口，主要特性：  · 查询交换机管理VLAN配置信息 · 修改交换机管理VLAN配置 

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.mgmt_vlan_response_dto import MgmtVlanResponseDto


class TestMgmtVlanResponseDto(unittest.TestCase):
    """ MgmtVlanResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMgmtVlanResponseDto(self):
        """
        Test MgmtVlanResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.mgmt_vlan_response_dto.MgmtVlanResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
