# coding: utf-8

"""
    PoE电源状态查询

    查询设备PoE电源状态。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.get_poe_power_state_api import GetPoePowerStateApi


class TestGetPoePowerStateApi(unittest.TestCase):
    """ GetPoePowerStateApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.get_poe_power_state_api.GetPoePowerStateApi()

    def tearDown(self):
        pass

    def test_get_poe_power_state(self):
        """
        Test case for get_poe_power_state

        查询PoE电源状态
        """
        pass


if __name__ == '__main__':
    unittest.main()
