# coding: utf-8

"""
    链路管理

    链路管理北向接口 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.notificate_service_api import NotificateServiceApi


class TestNotificateServiceApi(unittest.TestCase):
    """ NotificateServiceApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.notificate_service_api.NotificateServiceApi()

    def tearDown(self):
        pass

    def test_cancel_it_notificate_message(self):
        """
        Test case for cancel_it_notificate_message

        取消订阅IT设备链路变更通知
        """
        pass

    def test_cancel_network_notificate_message(self):
        """
        Test case for cancel_network_notificate_message

        取消订阅网络链路变更通知
        """
        pass

    def test_do_get(self):
        """
        Test case for do_get

        查询网络链路列表信息
        """
        pass

    def test_query_it_links(self):
        """
        Test case for query_it_links

        查询IT设备链路信息
        """
        pass

    def test_suscrbie_it_link_change_message(self):
        """
        Test case for suscrbie_it_link_change_message

        订阅IT设备链路变更通知
        """
        pass

    def test_suscrbie_network_link_change_message(self):
        """
        Test case for suscrbie_network_link_change_message

        订阅网络链路变更通知
        """
        pass


if __name__ == '__main__':
    unittest.main()
