# coding: utf-8

"""
    终端用户认证授权

    终端用户认证开放API 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.portal_auth_api import PortalAuthApi


class TestPortalAuthApi(unittest.TestCase):
    """ PortalAuthApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.portal_auth_api.PortalAuthApi()

    def tearDown(self):
        pass

    def test_get_authorization_result(self):
        """
        Test case for get_authorization_result

        查询认证结果
        """
        pass

    def test_portal_auth_login(self):
        """
        Test case for portal_auth_login

        认证终端用户
        """
        pass

    def test_portal_auth_logout(self):
        """
        Test case for portal_auth_logout

        注销终端用户
        """
        pass


if __name__ == '__main__':
    unittest.main()
