# coding: utf-8

"""
    站点模板SNMP配置

    站点模板SNMP配置第三方接口说明。 

    OpenAPI spec version: 1.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.site_template_snmp_dto import SiteTemplateSnmpDto


class TestSiteTemplateSnmpDto(unittest.TestCase):
    """ SiteTemplateSnmpDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteTemplateSnmpDto(self):
        """
        Test SiteTemplateSnmpDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.site_template_snmp_dto.SiteTemplateSnmpDto()
        pass


if __name__ == '__main__':
    unittest.main()
