# coding: utf-8

"""
    防火墙特征库升级

    防火墙特征库升级接口 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.fail_bean import FailBean


class TestFailBean(unittest.TestCase):
    """ FailBean unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFailBean(self):
        """
        Test FailBean
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.fail_bean.FailBean()
        pass


if __name__ == '__main__':
    unittest.main()
