# coding: utf-8

"""
    防火墙ASPF配置

    防火墙配置ASPF第三方接口，主要特性： · 查询ASPF配置 · 修改ASPF配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.aspf_northbound_api import AspfNorthboundApi


class TestAspfNorthboundApi(unittest.TestCase):
    """ AspfNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.aspf_northbound_api.AspfNorthboundApi()

    def tearDown(self):
        pass

    def test_get_aspf_config(self):
        """
        Test case for get_aspf_config

        查询ASPF配置
        """
        pass

    def test_modify_aspf_config(self):
        """
        Test case for modify_aspf_config

        修改ASPF配置
        """
        pass


if __name__ == '__main__':
    unittest.main()
