# coding: utf-8

"""
    TACACS配置

    TACACS配置北向接口，主要特性： · 配置TACACS · 查询TACACS 

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.net_work_service_tacacs_api import NetWorkServiceTacacsApi


class TestNetWorkServiceTacacsApi(unittest.TestCase):
    """ NetWorkServiceTacacsApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.net_work_service_tacacs_api.NetWorkServiceTacacsApi()

    def tearDown(self):
        pass

    def test_get_tacacs_config(self):
        """
        Test case for get_tacacs_config

        查询TACACS信息
        """
        pass

    def test_update_tacacs_config(self):
        """
        Test case for update_tacacs_config

        修改TACACS信息
        """
        pass


if __name__ == '__main__':
    unittest.main()
