# coding: utf-8

"""
    AP DHCP配置

    AP DHCP配置第三方接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ap_dhcp_config_responses_dto import ApDhcpConfigResponsesDto


class TestApDhcpConfigResponsesDto(unittest.TestCase):
    """ ApDhcpConfigResponsesDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApDhcpConfigResponsesDto(self):
        """
        Test ApDhcpConfigResponsesDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ap_dhcp_config_responses_dto.ApDhcpConfigResponsesDto()
        pass


if __name__ == '__main__':
    unittest.main()
