# coding: utf-8

"""
    TACACS模板管理

    TACACS模板配置北向接口，主要特性：  * 创建tacacs模板。 * 修改tacacs模板。 * 查询tacacs模板。 * 删除tacacs模板。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.get_tacacs_tmpl_response import GetTacacsTmplResponse


class TestGetTacacsTmplResponse(unittest.TestCase):
    """ GetTacacsTmplResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTacacsTmplResponse(self):
        """
        Test GetTacacsTmplResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.get_tacacs_tmpl_response.GetTacacsTmplResponse()
        pass


if __name__ == '__main__':
    unittest.main()
