# coding: utf-8

"""
    站点模板管理

    站点模板第三方接口说明。 

    OpenAPI spec version: 1.2.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.delete_site_temp_response_dto_fail import DeleteSiteTempResponseDtoFail


class TestDeleteSiteTempResponseDtoFail(unittest.TestCase):
    """ DeleteSiteTempResponseDtoFail unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteSiteTempResponseDtoFail(self):
        """
        Test DeleteSiteTempResponseDtoFail
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.delete_site_temp_response_dto_fail.DeleteSiteTempResponseDtoFail()
        pass


if __name__ == '__main__':
    unittest.main()
