# coding: utf-8

"""
    AP SSID配置管理

    AP SSID第三方接口。

    OpenAPI spec version: 1.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ssid_config_dto import SsidConfigDto


class TestSsidConfigDto(unittest.TestCase):
    """ SsidConfigDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSsidConfigDto(self):
        """
        Test SsidConfigDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ssid_config_dto.SsidConfigDto()
        pass


if __name__ == '__main__':
    unittest.main()
