# coding: utf-8

"""
    时间模板管理

    时间模板第三方接口说明。 

    OpenAPI spec version: 1.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.time_info import TimeInfo


class TestTimeInfo(unittest.TestCase):
    """ TimeInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeInfo(self):
        """
        Test TimeInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.time_info.TimeInfo()
        pass


if __name__ == '__main__':
    unittest.main()
