# coding: utf-8

"""
    PoE电源状态查询

    查询设备PoE电源状态。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.get_poe_power_state_resp import GetPoePowerStateResp


class TestGetPoePowerStateResp(unittest.TestCase):
    """ GetPoePowerStateResp unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPoePowerStateResp(self):
        """
        Test GetPoePowerStateResp
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.get_poe_power_state_resp.GetPoePowerStateResp()
        pass


if __name__ == '__main__':
    unittest.main()
