# coding: utf-8

"""
    交换机STP配置

    LSW STP配置北向接口，主要特性： · 查询交换STP配置信息 · 修改交换机STP配置 · 删除交换机STP配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.incre_mstp_region import IncreMstpRegion


class TestIncreMstpRegion(unittest.TestCase):
    """ IncreMstpRegion unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncreMstpRegion(self):
        """
        Test IncreMstpRegion
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.incre_mstp_region.IncreMstpRegion()
        pass


if __name__ == '__main__':
    unittest.main()
