# coding: utf-8

"""
    License管理

    公有云license管理接口。 场景：对租户license操作的第三方接口。 

    OpenAPI spec version: 1.0.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.import_active_code_out import ImportActiveCodeOut


class TestImportActiveCodeOut(unittest.TestCase):
    """ ImportActiveCodeOut unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportActiveCodeOut(self):
        """
        Test ImportActiveCodeOut
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.import_active_code_out.ImportActiveCodeOut()
        pass


if __name__ == '__main__':
    unittest.main()
