# coding: utf-8

"""
    配置保存

    配置保存接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.config_save_api_northbound_api import ConfigSaveApiNorthboundApi


class TestConfigSaveApiNorthboundApi(unittest.TestCase):
    """ ConfigSaveApiNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.config_save_api_northbound_api.ConfigSaveApiNorthboundApi()

    def tearDown(self):
        pass

    def test_config_save(self):
        """
        Test case for config_save

        保存配置
        """
        pass

    def test_query_config_save(self):
        """
        Test case for query_config_save

        查询保存结果
        """
        pass


if __name__ == '__main__':
    unittest.main()
