# coding: utf-8

"""
    射频管理国家码查询

    射频管理国家码第三方北向接口。     

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.sysconfig_service_api import SysconfigServiceApi


class TestSysconfigServiceApi(unittest.TestCase):
    """ SysconfigServiceApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.sysconfig_service_api.SysconfigServiceApi()

    def tearDown(self):
        pass

    def test_get_radio_country_channel(self):
        """
        Test case for get_radio_country_channel

        查询射频管理国家码
        """
        pass


if __name__ == '__main__':
    unittest.main()
