# coding: utf-8

"""
    AP DHCP配置

    AP DHCP配置第三方接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.apdhcp_cfg_northbound_api import ApdhcpCfgNorthboundApi


class TestApdhcpCfgNorthboundApi(unittest.TestCase):
    """ ApdhcpCfgNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.apdhcp_cfg_northbound_api.ApdhcpCfgNorthboundApi()

    def tearDown(self):
        pass

    def test_get_site_dhcp_config(self):
        """
        Test case for get_site_dhcp_config

        查询站点全局DHCP配置
        """
        pass

    def test_update_site_dhcp_config(self):
        """
        Test case for update_site_dhcp_config

        修改站点全局DHCP配置
        """
        pass


if __name__ == '__main__':
    unittest.main()
