# coding: utf-8

"""
    单板管理

    单板管理第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.config_response_dto import ConfigResponseDto


class TestConfigResponseDto(unittest.TestCase):
    """ ConfigResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigResponseDto(self):
        """
        Test ConfigResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.config_response_dto.ConfigResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
