# coding: utf-8

"""
    AP网口IOT插卡管理

    AP网口IOT插卡查询及操作接口。 场景：对AP网口IOT插卡查询及操作的第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.iot_card_operation_dto import IotCardOperationDto


class TestIotCardOperationDto(unittest.TestCase):
    """ IotCardOperationDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIotCardOperationDto(self):
        """
        Test IotCardOperationDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.iot_card_operation_dto.IotCardOperationDto()
        pass


if __name__ == '__main__':
    unittest.main()
