# coding: utf-8

"""
    AP SSID配置管理

    AP SSID第三方接口。

    OpenAPI spec version: 1.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.delete_ssid_response import DeleteSsidResponse


class TestDeleteSsidResponse(unittest.TestCase):
    """ DeleteSsidResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteSsidResponse(self):
        """
        Test DeleteSsidResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.delete_ssid_response.DeleteSsidResponse()
        pass


if __name__ == '__main__':
    unittest.main()
