# coding: utf-8

"""
    交换机STP配置

    LSW STP配置北向接口，主要特性： · 查询交换STP配置信息 · 修改交换机STP配置 · 删除交换机STP配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.incre_region_instance_device import IncreRegionInstanceDevice


class TestIncreRegionInstanceDevice(unittest.TestCase):
    """ IncreRegionInstanceDevice unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncreRegionInstanceDevice(self):
        """
        Test IncreRegionInstanceDevice
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.incre_region_instance_device.IncreRegionInstanceDevice()
        pass


if __name__ == '__main__':
    unittest.main()
