# coding: utf-8

"""
    设备升级

    · 查询设备文件 · 创建站点升级 · 查询站点升级 · 查询设备升级 · 取消设备升级 · 删除站点升级 · 重新升级设备 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.policy_config_res import PolicyConfigRes


class TestPolicyConfigRes(unittest.TestCase):
    """ PolicyConfigRes unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyConfigRes(self):
        """
        Test PolicyConfigRes
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.policy_config_res.PolicyConfigRes()
        pass


if __name__ == '__main__':
    unittest.main()
