# coding: utf-8

"""
    终端应用流量信息查询

    终端TopN应用流量查询。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.application_open_api_api import ApplicationOpenApiApi


class TestApplicationOpenApiApi(unittest.TestCase):
    """ ApplicationOpenApiApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.application_open_api_api.ApplicationOpenApiApi()

    def tearDown(self):
        pass

    def test_query_application_info(self):
        """
        Test case for query_application_info

        查询终端TopN应用流量
        """
        pass


if __name__ == '__main__':
    unittest.main()
