# coding: utf-8

"""
    AP站点模板SSID配置

    AP站点模板SSID第三方接口说明。 

    OpenAPI spec version: 1.5.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.site_template_delete_ssid_response import SiteTemplateDeleteSsidResponse


class TestSiteTemplateDeleteSsidResponse(unittest.TestCase):
    """ SiteTemplateDeleteSsidResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteTemplateDeleteSsidResponse(self):
        """
        Test SiteTemplateDeleteSsidResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.site_template_delete_ssid_response.SiteTemplateDeleteSsidResponse()
        pass


if __name__ == '__main__':
    unittest.main()
