# coding: utf-8

"""
    链路管理

    链路管理北向接口 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.inform_message import InformMessage


class TestInformMessage(unittest.TestCase):
    """ InformMessage unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInformMessage(self):
        """
        Test InformMessage
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.inform_message.InformMessage()
        pass


if __name__ == '__main__':
    unittest.main()
