# coding: utf-8

"""
    AP站点模板射频配置

    AP站点模板射频配置第三方接口说明。 

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.site_template_group_radio_response_dto import SiteTemplateGroupRadioResponseDto


class TestSiteTemplateGroupRadioResponseDto(unittest.TestCase):
    """ SiteTemplateGroupRadioResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteTemplateGroupRadioResponseDto(self):
        """
        Test SiteTemplateGroupRadioResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.site_template_group_radio_response_dto.SiteTemplateGroupRadioResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
