# coding: utf-8

"""
    AP页面推送策略

    AP页面推送策略开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.common_portal_page_rule_output_dto import CommonPortalPageRuleOutputDto


class TestCommonPortalPageRuleOutputDto(unittest.TestCase):
    """ CommonPortalPageRuleOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonPortalPageRuleOutputDto(self):
        """
        Test CommonPortalPageRuleOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.common_portal_page_rule_output_dto.CommonPortalPageRuleOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
