# coding: utf-8

"""
    AP SSID配置管理

    AP SSID第三方接口。

    OpenAPI spec version: 1.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.radius_content_dto import RadiusContentDto


class TestRadiusContentDto(unittest.TestCase):
    """ RadiusContentDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRadiusContentDto(self):
        """
        Test RadiusContentDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.radius_content_dto.RadiusContentDto()
        pass


if __name__ == '__main__':
    unittest.main()
