# coding: utf-8

"""
    单板管理

    单板管理第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.board_info_dto import BoardInfoDto


class TestBoardInfoDto(unittest.TestCase):
    """ BoardInfoDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBoardInfoDto(self):
        """
        Test BoardInfoDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.board_info_dto.BoardInfoDto()
        pass


if __name__ == '__main__':
    unittest.main()
