# coding: utf-8

"""
    TACACS模板管理

    TACACS模板配置北向接口，主要特性：  * 创建tacacs模板。 * 修改tacacs模板。 * 查询tacacs模板。 * 删除tacacs模板。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.net_work_service_tacacs_tmpl_api import NetWorkServiceTacacsTmplApi


class TestNetWorkServiceTacacsTmplApi(unittest.TestCase):
    """ NetWorkServiceTacacsTmplApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.net_work_service_tacacs_tmpl_api.NetWorkServiceTacacsTmplApi()

    def tearDown(self):
        pass

    def test_create_tacacs_tmpl(self):
        """
        Test case for create_tacacs_tmpl

        创建TACACS模板
        """
        pass

    def test_delete_tacacs_tmpl(self):
        """
        Test case for delete_tacacs_tmpl

        删除TACACS模板
        """
        pass

    def test_edit_tacacs_tmpl(self):
        """
        Test case for edit_tacacs_tmpl

        修改TACACS模板
        """
        pass

    def test_get_tacacs_tmpl(self):
        """
        Test case for get_tacacs_tmpl

        查询TACACS模板
        """
        pass


if __name__ == '__main__':
    unittest.main()
