# coding: utf-8

"""
    本地用户配置管理

    本地用户配置北向接口，主要特性： · 查询本地用户配置 · 修改本地用户配置 · 创建本地用户配置 

    OpenAPI spec version: 1.2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.net_work_service_local_user_api import NetWorkServiceLocalUserApi


class TestNetWorkServiceLocalUserApi(unittest.TestCase):
    """ NetWorkServiceLocalUserApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.net_work_service_local_user_api.NetWorkServiceLocalUserApi()

    def tearDown(self):
        pass

    def test_create_localuser_info(self):
        """
        Test case for create_localuser_info

        创建本地用户
        """
        pass

    def test_create_template_localuser_info(self):
        """
        Test case for create_template_localuser_info

        创建站点模板的本地用户
        """
        pass

    def test_delete_localuser_info(self):
        """
        Test case for delete_localuser_info

        删除本地用户
        """
        pass

    def test_delete_template_localuser_info(self):
        """
        Test case for delete_template_localuser_info

        删除本地用户
        """
        pass

    def test_get_localuser_info(self):
        """
        Test case for get_localuser_info

        查询本地用户
        """
        pass

    def test_get_template_localuser_info(self):
        """
        Test case for get_template_localuser_info

        查询站点模板的本地用户
        """
        pass

    def test_init_loginuser_info(self):
        """
        Test case for init_loginuser_info

        配置租户下设备admin账号的默认密码
        """
        pass

    def test_update_localuser_info(self):
        """
        Test case for update_localuser_info

        修改本地用户
        """
        pass

    def test_update_template_localuser_info(self):
        """
        Test case for update_template_localuser_info

        修改站点模板的本地用户
        """
        pass


if __name__ == '__main__':
    unittest.main()
