# coding: utf-8

"""
    站点内AP增值服务配置

    站点内AP增值服务配置北向接口，主要特性： * 查询站点内AP增值服务配置。 * 修改站点内AP增值服务配置。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ap_extra_service_response_dto import ApExtraServiceResponseDto


class TestApExtraServiceResponseDto(unittest.TestCase):
    """ ApExtraServiceResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApExtraServiceResponseDto(self):
        """
        Test ApExtraServiceResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ap_extra_service_response_dto.ApExtraServiceResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
