# coding: utf-8

"""
    实体资源北向接口

    实体资源条件查询。 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ot_point_res_data import OTPointResData


class TestOTPointResData(unittest.TestCase):
    """ OTPointResData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOTPointResData(self):
        """
        Test OTPointResData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ot_point_res_data.OTPointResData()
        pass


if __name__ == '__main__':
    unittest.main()
