# coding: utf-8

"""
    AP设备射频配置

    AP设备射频配置第三方接口说明。 

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.ap_radio_config_northbound_api import ApRadioConfigNorthboundApi


class TestApRadioConfigNorthboundApi(unittest.TestCase):
    """ ApRadioConfigNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.ap_radio_config_northbound_api.ApRadioConfigNorthboundApi()

    def tearDown(self):
        pass

    def test_get_device_radio_config(self):
        """
        Test case for get_device_radio_config

        查询AP设备射频配置信息
        """
        pass

    def test_update_device_radio_config(self):
        """
        Test case for update_device_radio_config

        修改AP设备射频配置信息
        """
        pass


if __name__ == '__main__':
    unittest.main()
