# coding: utf-8

"""
    终端用户管理

    终端用户管理开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.client_user_manager_api import ClientUserManagerApi


class TestClientUserManagerApi(unittest.TestCase):
    """ ClientUserManagerApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.client_user_manager_api.ClientUserManagerApi()

    def tearDown(self):
        pass

    def test_cut_user(self):
        """
        Test case for cut_user

        强制用户下线
        """
        pass

    def test_get_authorizationresult(self):
        """
        Test case for get_authorizationresult

        查询授权结果
        """
        pass

    def test_user_authorization(self):
        """
        Test case for user_authorization

        授权终端用户
        """
        pass


if __name__ == '__main__':
    unittest.main()
