# coding: utf-8

"""
    控制器支持第三方系统通过API接口获取用户上下线信息

    控制器支持第三方系统通过API接口获取用户上下线信息 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.authentication_log_api import AuthenticationLogApi


class TestAuthenticationLogApi(unittest.TestCase):
    """ AuthenticationLogApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.authentication_log_api.AuthenticationLogApi()

    def tearDown(self):
        pass

    def test_get_authentication_log_info_list(self):
        """
        Test case for get_authentication_log_info_list

        查询用户上下线日志信息
        """
        pass


if __name__ == '__main__':
    unittest.main()
