# coding: utf-8

"""
    用户管理

    用户管理第三方北向接口。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.delete_user_input_dto import DeleteUserInputDto


class TestDeleteUserInputDto(unittest.TestCase):
    """ DeleteUserInputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteUserInputDto(self):
        """
        Test DeleteUserInputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.delete_user_input_dto.DeleteUserInputDto()
        pass


if __name__ == '__main__':
    unittest.main()
