# coding: utf-8

"""
    框式交换机板卡信息操作

    框式上云相关操作接口： 场景：对框式交换机信息查询操作的第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.campus_sw_operation_openapi_api import CampusSWOperationOpenapiApi


class TestCampusSWOperationOpenapiApi(unittest.TestCase):
    """ CampusSWOperationOpenapiApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.campus_sw_operation_openapi_api.CampusSWOperationOpenapiApi()

    def tearDown(self):
        pass

    def test_get_fan_info(self):
        """
        Test case for get_fan_info

        查询设备风扇信息
        """
        pass

    def test_get_power_info(self):
        """
        Test case for get_power_info

        查询设备电源信息
        """
        pass

    def test_get_reset_reason(self):
        """
        Test case for get_reset_reason

        查询指定单板复位原因
        """
        pass

    def test_get_system_power_info(self):
        """
        Test case for get_system_power_info

        查询设备系统电源信息
        """
        pass

    def test_power_supply(self):
        """
        Test case for power_supply

        配置单板上下电
        """
        pass

    def test_query_all_boards(self):
        """
        Test case for query_all_boards

        查询插卡框式交换机单板信息
        """
        pass

    def test_query_interface_detail(self):
        """
        Test case for query_interface_detail

        查询单板接口信息
        """
        pass

    def test_reset_board(self):
        """
        Test case for reset_board

        复位单板
        """
        pass

    def test_reset_chassis(self):
        """
        Test case for reset_chassis

        框式交换机整框重启
        """
        pass

    def test_switchover(self):
        """
        Test case for switchover

        框式交换机主备倒换
        """
        pass


if __name__ == '__main__':
    unittest.main()
