# coding: utf-8

"""
    SSH客户端首次认证免公钥配置

    SSH客户端首次认证免公钥配置北向接口，主要特性： · 查询SSH客户端首次认证免公钥配置 · 修改SSH客户端首次认证免公钥配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ssh_first_enable_response_dto import SSHFirstEnableResponseDto


class TestSSHFirstEnableResponseDto(unittest.TestCase):
    """ SSHFirstEnableResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSSHFirstEnableResponseDto(self):
        """
        Test SSHFirstEnableResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ssh_first_enable_response_dto.SSHFirstEnableResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
