# coding: utf-8

"""
    拓扑管理

    拓扑管理第三方北向接口。 1、查询LACP LAG信息 2、查询LLDP信息 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.neighbors_info_dto import NeighborsInfoDto


class TestNeighborsInfoDto(unittest.TestCase):
    """ NeighborsInfoDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNeighborsInfoDto(self):
        """
        Test NeighborsInfoDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.neighbors_info_dto.NeighborsInfoDto()
        pass


if __name__ == '__main__':
    unittest.main()
