# coding: utf-8

"""
    路由器设备静态路由配置

    路由器设备静态路由配置第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.get_ar_staticroute_response_dto import GetArStaticrouteResponseDto


class TestGetArStaticrouteResponseDto(unittest.TestCase):
    """ GetArStaticrouteResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetArStaticrouteResponseDto(self):
        """
        Test GetArStaticrouteResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.get_ar_staticroute_response_dto.GetArStaticrouteResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
