# coding: utf-8

"""
    站点模板管理

    站点模板第三方接口说明。 

    OpenAPI spec version: 1.2.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.update_site_temp_dto import UpdateSiteTempDto


class TestUpdateSiteTempDto(unittest.TestCase):
    """ UpdateSiteTempDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSiteTempDto(self):
        """
        Test UpdateSiteTempDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.update_site_temp_dto.UpdateSiteTempDto()
        pass


if __name__ == '__main__':
    unittest.main()
