# coding: utf-8

"""
    防火墙设备静态路由配置

    防火墙设备静态路由配置第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.fw_static_route_info_dto import FwStaticRouteInfoDto


class TestFwStaticRouteInfoDto(unittest.TestCase):
    """ FwStaticRouteInfoDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFwStaticRouteInfoDto(self):
        """
        Test FwStaticRouteInfoDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.fw_static_route_info_dto.FwStaticRouteInfoDto()
        pass


if __name__ == '__main__':
    unittest.main()
