# coding: utf-8

"""
    堆叠管理

    堆叠管理第三方接口。 场景：创建堆叠操作的第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.create_stack_out_dto import CreateStackOutDto


class TestCreateStackOutDto(unittest.TestCase):
    """ CreateStackOutDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateStackOutDto(self):
        """
        Test CreateStackOutDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.create_stack_out_dto.CreateStackOutDto()
        pass


if __name__ == '__main__':
    unittest.main()
