# coding: utf-8

"""
    终端客流量数据信息查询

    1、查询设备标签。 2、查询历史客户流量。 3、查询实时客户流量，返回最近5分钟内接入客户流量。 4、查询访客、路人、接入用户的历史趋势。 5、查询访客驻留时长的历史趋势。 6、查询回头客记录。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.endpointanls_open_api_api import EndpointanlsOpenApiApi


class TestEndpointanlsOpenApiApi(unittest.TestCase):
    """ EndpointanlsOpenApiApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.endpointanls_open_api_api.EndpointanlsOpenApiApi()

    def tearDown(self):
        pass

    def test_get_device_group_tags(self):
        """
        Test case for get_device_group_tags

        获取设备标签
        """
        pass

    def test_get_history_flow_distr(self):
        """
        Test case for get_history_flow_distr

        查询历史接入客户数量
        """
        pass

    def test_get_realtime_flow_distr(self):
        """
        Test case for get_realtime_flow_distr

        查询实时接入客户数量
        """
        pass

    def test_query_capture_rate_distr(self):
        """
        Test case for query_capture_rate_distr

        查询访客、路人、接入用户的历史趋势
        """
        pass

    def test_query_dwell_time_distr(self):
        """
        Test case for query_dwell_time_distr

        查询访客驻留时长的历史趋势
        """
        pass

    def test_query_loyalty_distr(self):
        """
        Test case for query_loyalty_distr

        查询回头客记录
        """
        pass


if __name__ == '__main__':
    unittest.main()
