# coding: utf-8

"""
    站点内设备域名配置

    站点内设备域名配置北向接口，主要特性： · 查询站点内设备域名配置 · 修改站点内设备域名配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.domain_name_northbound_api import DomainNameNorthboundApi


class TestDomainNameNorthboundApi(unittest.TestCase):
    """ DomainNameNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.domain_name_northbound_api.DomainNameNorthboundApi()

    def tearDown(self):
        pass

    def test_config(self):
        """
        Test case for config

        修改站点内设备域名配置
        """
        pass

    def test_get_config(self):
        """
        Test case for get_config

        获取站点内设备域名配置
        """
        pass


if __name__ == '__main__':
    unittest.main()
