# coding: utf-8

"""
    ACL模板管理

    ACL模板第三方管理接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.acl_template_nb_north_bound_api import AclTemplateNBNorthBoundApi


class TestAclTemplateNBNorthBoundApi(unittest.TestCase):
    """ AclTemplateNBNorthBoundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.acl_template_nb_north_bound_api.AclTemplateNBNorthBoundApi()

    def tearDown(self):
        pass

    def test_add_acl_template(self):
        """
        Test case for add_acl_template

        创建ACL模板
        """
        pass

    def test_delete_acl_template(self):
        """
        Test case for delete_acl_template

        删除ACL模板
        """
        pass

    def test_get_acl_template(self):
        """
        Test case for get_acl_template

        查询ACL模板
        """
        pass

    def test_update_acl_template(self):
        """
        Test case for update_acl_template

        更新ACL模板
        """
        pass


if __name__ == '__main__':
    unittest.main()
