# coding: utf-8

"""
    ACL模板管理

    ACL模板第三方管理接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.delete_template_dto import DeleteTemplateDto


class TestDeleteTemplateDto(unittest.TestCase):
    """ DeleteTemplateDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteTemplateDto(self):
        """
        Test DeleteTemplateDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.delete_template_dto.DeleteTemplateDto()
        pass


if __name__ == '__main__':
    unittest.main()
