# coding: utf-8

"""
    AP站点模板射频配置

    AP站点模板射频配置第三方接口说明。 

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.site_template_groupradio_netcfg_northbound_api import SiteTemplateGroupradioNetcfgNorthboundApi


class TestSiteTemplateGroupradioNetcfgNorthboundApi(unittest.TestCase):
    """ SiteTemplateGroupradioNetcfgNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.site_template_groupradio_netcfg_northbound_api.SiteTemplateGroupradioNetcfgNorthboundApi()

    def tearDown(self):
        pass

    def test_get_site_template_group_radio(self):
        """
        Test case for get_site_template_group_radio

        查询AP站点模板射频配置信息
        """
        pass

    def test_update_site_template_group_radio(self):
        """
        Test case for update_site_template_group_radio

        修改AP站点模板射频配置信息
        """
        pass


if __name__ == '__main__':
    unittest.main()
