# coding: utf-8

"""
    设备BootROM密码配置

    设备BootROM密码配置第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.boot_rom_netcfg_northbound_api import BootROMNetcfgNorthboundApi


class TestBootROMNetcfgNorthboundApi(unittest.TestCase):
    """ BootROMNetcfgNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.boot_rom_netcfg_northbound_api.BootROMNetcfgNorthboundApi()

    def tearDown(self):
        pass

    def test_config_init_boot_rom(self):
        """
        Test case for config_init_boot_rom

        配置租户BootROM密码
        """
        pass

    def test_update_site_boot_rom_config(self):
        """
        Test case for update_site_boot_rom_config

        配置站点BootROM密码
        """
        pass


if __name__ == '__main__':
    unittest.main()
