# coding: utf-8

"""
    ACL模板管理

    ACL模板第三方管理接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.upadate_acl_dto import UpadateAclDto


class TestUpadateAclDto(unittest.TestCase):
    """ UpadateAclDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpadateAclDto(self):
        """
        Test UpadateAclDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.upadate_acl_dto.UpadateAclDto()
        pass


if __name__ == '__main__':
    unittest.main()
