# coding: utf-8

"""
    运维ping/trace探测

    ping/trace探测第三方接口。 · 创建ping探测任务 · 查询ping探测结果 · 创建trace探测任务 · 查询trace探测结果 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ping_task_diagnose import PingTaskDiagnose


class TestPingTaskDiagnose(unittest.TestCase):
    """ PingTaskDiagnose unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPingTaskDiagnose(self):
        """
        Test PingTaskDiagnose
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ping_task_diagnose.PingTaskDiagnose()
        pass


if __name__ == '__main__':
    unittest.main()
