# coding: utf-8

"""
    用户组管理

    用户组管理开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.common_usergroup_output_dto import CommonUsergroupOutputDto


class TestCommonUsergroupOutputDto(unittest.TestCase):
    """ CommonUsergroupOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonUsergroupOutputDto(self):
        """
        Test CommonUsergroupOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.common_usergroup_output_dto.CommonUsergroupOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
