# coding: utf-8

"""
    PPSK帐号配置

    PPSK帐号管理北向接口，主要包括： · 创建PPSK帐号 · 修改PPSK帐号 · 删除PPSK帐号 · 查询PPSK帐号 

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.ppsk_northbound_api import PPSKNorthboundApi


class TestPPSKNorthboundApi(unittest.TestCase):
    """ PPSKNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.ppsk_northbound_api.PPSKNorthboundApi()

    def tearDown(self):
        pass

    def test_create_ppsk_account(self):
        """
        Test case for create_ppsk_account

        新增PPSK帐号
        """
        pass

    def test_delete_ppsk_account(self):
        """
        Test case for delete_ppsk_account

        删除PPSK帐号
        """
        pass

    def test_get_ppsk_account(self):
        """
        Test case for get_ppsk_account

        查询PPSK帐号
        """
        pass

    def test_update_ppsk_account(self):
        """
        Test case for update_ppsk_account

        修改PPSK帐号
        """
        pass


if __name__ == '__main__':
    unittest.main()
