# coding: utf-8

"""
    链路管理

    链路管理北向接口 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.north_rest_response import NorthRestResponse


class TestNorthRestResponse(unittest.TestCase):
    """ NorthRestResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNorthRestResponse(self):
        """
        Test NorthRestResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.north_rest_response.NorthRestResponse()
        pass


if __name__ == '__main__':
    unittest.main()
