# coding: utf-8

"""
    站点内AP设备Nat日志上报开关

    · 查询站点内AP设备Nat日志上报配置 · 配置站点内AP设备Nat日志上报信息 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.nat_session_log_config_param import NatSessionLogConfigParam


class TestNatSessionLogConfigParam(unittest.TestCase):
    """ NatSessionLogConfigParam unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNatSessionLogConfigParam(self):
        """
        Test NatSessionLogConfigParam
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.nat_session_log_config_param.NatSessionLogConfigParam()
        pass


if __name__ == '__main__':
    unittest.main()
