# coding: utf-8

"""
    拓扑管理

    拓扑管理第三方北向接口。 1、查询LACP LAG信息 2、查询LLDP信息 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.topo_mgr_service_api import TopoMgrServiceApi


class TestTopoMgrServiceApi(unittest.TestCase):
    """ TopoMgrServiceApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.topo_mgr_service_api.TopoMgrServiceApi()

    def tearDown(self):
        pass

    def test_get_lacp_lag_info(self):
        """
        Test case for get_lacp_lag_info

        查询LACP LAG信息
        """
        pass

    def test_get_neighbors_info(self):
        """
        Test case for get_neighbors_info

        查询LLDP信息
        """
        pass


if __name__ == '__main__':
    unittest.main()
