# coding: utf-8

"""
    TACACS模板管理

    TACACS模板配置北向接口，主要特性：  * 创建tacacs模板。 * 修改tacacs模板。 * 查询tacacs模板。 * 删除tacacs模板。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.create_tacacs_tmpl_response import CreateTacacsTmplResponse


class TestCreateTacacsTmplResponse(unittest.TestCase):
    """ CreateTacacsTmplResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTacacsTmplResponse(self):
        """
        Test CreateTacacsTmplResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.create_tacacs_tmpl_response.CreateTacacsTmplResponse()
        pass


if __name__ == '__main__':
    unittest.main()
