# coding: utf-8

"""
    用户组管理

    用户组管理开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.usergroup_output_dto import UsergroupOutputDto


class TestUsergroupOutputDto(unittest.TestCase):
    """ UsergroupOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsergroupOutputDto(self):
        """
        Test UsergroupOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.usergroup_output_dto.UsergroupOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
