# coding: utf-8

"""
    设备上报日志记录查询

    查询设备上报日志。

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.device_log_info import DeviceLogInfo


class TestDeviceLogInfo(unittest.TestCase):
    """ DeviceLogInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceLogInfo(self):
        """
        Test DeviceLogInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.device_log_info.DeviceLogInfo()
        pass


if __name__ == '__main__':
    unittest.main()
