# coding: utf-8

"""
    路由器设备静态路由配置

    路由器设备静态路由配置第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.ar_staticroute_netcfg_northbound_api import ArStaticrouteNetcfgNorthboundApi


class TestArStaticrouteNetcfgNorthboundApi(unittest.TestCase):
    """ ArStaticrouteNetcfgNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.ar_staticroute_netcfg_northbound_api.ArStaticrouteNetcfgNorthboundApi()

    def tearDown(self):
        pass

    def test_create_device_ar_staticroute_config(self):
        """
        Test case for create_device_ar_staticroute_config

        创建路由器设备静态路由配置
        """
        pass

    def test_delete_device_ar_staticroute_config(self):
        """
        Test case for delete_device_ar_staticroute_config

        删除路由器设备静态路由配置
        """
        pass

    def test_get_device_ar_staticroute_config(self):
        """
        Test case for get_device_ar_staticroute_config

        查询路由器设备静态路由配置
        """
        pass

    def test_update_device_ar_staticroute_config(self):
        """
        Test case for update_device_ar_staticroute_config

        修改路由器设备静态路由配置
        """
        pass


if __name__ == '__main__':
    unittest.main()
