# coding: utf-8

"""
    AP网口IOT插卡管理

    AP网口IOT插卡查询及操作接口。 场景：对AP网口IOT插卡查询及操作的第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ethernet_card_dto import EthernetCardDto


class TestEthernetCardDto(unittest.TestCase):
    """ EthernetCardDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEthernetCardDto(self):
        """
        Test EthernetCardDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ethernet_card_dto.EthernetCardDto()
        pass


if __name__ == '__main__':
    unittest.main()
