# coding: utf-8

"""
    mac帐号管理

    mac帐号管理

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.data_mac_dto import DataMacDto


class TestDataMacDto(unittest.TestCase):
    """ DataMacDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataMacDto(self):
        """
        Test DataMacDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.data_mac_dto.DataMacDto()
        pass


if __name__ == '__main__':
    unittest.main()
