# coding: utf-8

"""
    WAC关联Fit AP管理

    WAC关联Fit AP第三方接口，主要特性：  · 根据指定的WAC设备ID查询关联的Fit AP列表 · 根据指定的WAC设备关联Fit AP列表 · 根据指定的WAC设备解除关联的Fit AP列表 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.fit_ap_info import FitApInfo


class TestFitApInfo(unittest.TestCase):
    """ FitApInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFitApInfo(self):
        """
        Test FitApInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.fit_ap_info.FitApInfo()
        pass


if __name__ == '__main__':
    unittest.main()
