# coding: utf-8

"""
    设备定时重启

    · 创建或修改定时重启、延时重启设备任务 · 查询重启设备任务的状态 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.period_reboot_device_api import PeriodRebootDeviceApi


class TestPeriodRebootDeviceApi(unittest.TestCase):
    """ PeriodRebootDeviceApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.period_reboot_device_api.PeriodRebootDeviceApi()

    def tearDown(self):
        pass

    def test_get_reboot_task_status(self):
        """
        Test case for get_reboot_task_status

        查询设备定时重启任务
        """
        pass

    def test_period_reboot_device(self):
        """
        Test case for period_reboot_device

        设置设备定时重启任务
        """
        pass


if __name__ == '__main__':
    unittest.main()
