# coding: utf-8

"""
    站点模板管理

    站点模板第三方接口说明。 

    OpenAPI spec version: 1.2.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.site_template_and_site_list_response_dto_fail import SiteTemplateAndSiteListResponseDtoFail


class TestSiteTemplateAndSiteListResponseDtoFail(unittest.TestCase):
    """ SiteTemplateAndSiteListResponseDtoFail unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSiteTemplateAndSiteListResponseDtoFail(self):
        """
        Test SiteTemplateAndSiteListResponseDtoFail
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.site_template_and_site_list_response_dto_fail.SiteTemplateAndSiteListResponseDtoFail()
        pass


if __name__ == '__main__':
    unittest.main()
