# coding: utf-8

"""
    防火墙设备静态路由配置

    防火墙设备静态路由配置第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.get_fw_static_route_response_dto import GetFwStaticRouteResponseDto


class TestGetFwStaticRouteResponseDto(unittest.TestCase):
    """ GetFwStaticRouteResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetFwStaticRouteResponseDto(self):
        """
        Test GetFwStaticRouteResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.get_fw_static_route_response_dto.GetFwStaticRouteResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
