# coding: utf-8

"""
    Portal在线用户查询

    查询Portal在线用户第三方北向接口。提供了Portal在线用户的查询、强制下线接口。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.query_portal_online_user_info_output_dto import QueryPortalOnlineUserInfoOutputDto


class TestQueryPortalOnlineUserInfoOutputDto(unittest.TestCase):
    """ QueryPortalOnlineUserInfoOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryPortalOnlineUserInfoOutputDto(self):
        """
        Test QueryPortalOnlineUserInfoOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.query_portal_online_user_info_output_dto.QueryPortalOnlineUserInfoOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
