# coding: utf-8

"""
    交换机STP保护配置

    主要特性： · 创建交换机STP保护配置 · 修改交换机STP保护配置 · 查询交换机STP保护配置 · 删除交换机STP保护配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.lsw_stp_protection_northbound_api import LSWStpProtectionNorthboundApi


class TestLSWStpProtectionNorthboundApi(unittest.TestCase):
    """ LSWStpProtectionNorthboundApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.lsw_stp_protection_northbound_api.LSWStpProtectionNorthboundApi()

    def tearDown(self):
        pass

    def test_create_stp_protection(self):
        """
        Test case for create_stp_protection

        创建交换机STP保护配置
        """
        pass

    def test_delete_stp_protection(self):
        """
        Test case for delete_stp_protection

        删除交换机STP保护配置
        """
        pass

    def test_get_stp_protection(self):
        """
        Test case for get_stp_protection

        查询交换机STP保护配置
        """
        pass

    def test_update_stp_protection(self):
        """
        Test case for update_stp_protection

        修改交换机STP保护配置
        """
        pass


if __name__ == '__main__':
    unittest.main()
