# coding: utf-8

"""
    AP页面推送策略

    AP页面推送策略开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.get_portal_page_rule_output_dto import GetPortalPageRuleOutputDto


class TestGetPortalPageRuleOutputDto(unittest.TestCase):
    """ GetPortalPageRuleOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPortalPageRuleOutputDto(self):
        """
        Test GetPortalPageRuleOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.get_portal_page_rule_output_dto.GetPortalPageRuleOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
