# coding: utf-8

"""
    站点内AP增值服务配置

    站点内AP增值服务配置北向接口，主要特性： * 查询站点内AP增值服务配置。 * 修改站点内AP增值服务配置。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.data_upload_dto import DataUploadDto


class TestDataUploadDto(unittest.TestCase):
    """ DataUploadDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataUploadDto(self):
        """
        Test DataUploadDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.data_upload_dto.DataUploadDto()
        pass


if __name__ == '__main__':
    unittest.main()
