# coding: utf-8

"""
    PPSK帐号配置

    PPSK帐号管理北向接口，主要包括： · 创建PPSK帐号 · 修改PPSK帐号 · 删除PPSK帐号 · 查询PPSK帐号 

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.base_response_dto import BaseResponseDto


class TestBaseResponseDto(unittest.TestCase):
    """ BaseResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseResponseDto(self):
        """
        Test BaseResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.base_response_dto.BaseResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
