# coding: utf-8

"""
    AP网口IOT插卡管理

    AP网口IOT插卡查询及操作接口。 场景：对AP网口IOT插卡查询及操作的第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.ap_iot_card_openapi_api import ApIotCardOpenapiApi


class TestApIotCardOpenapiApi(unittest.TestCase):
    """ ApIotCardOpenapiApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.ap_iot_card_openapi_api.ApIotCardOpenapiApi()

    def tearDown(self):
        pass

    def test_card_operation(self):
        """
        Test case for card_operation

        操作AP网口IOT插卡
        """
        pass

    def test_exec_iot_command(self):
        """
        Test case for exec_iot_command

        给IOT插卡下命令
        """
        pass

    def test_query_ethernet_card_list(self):
        """
        Test case for query_ethernet_card_list

        查询AP网口IOT插卡
        """
        pass

    def test_query_iot_command_result(self):
        """
        Test case for query_iot_command_result

        查询AP IOT命令下发的状态
        """
        pass


if __name__ == '__main__':
    unittest.main()
