# coding: utf-8

"""
    网络设备管理

    提供北向查询网络设备服务。 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.ne_list_open_api_service_api import NeListOpenApiServiceApi


class TestNeListOpenApiServiceApi(unittest.TestCase):
    """ NeListOpenApiServiceApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.ne_list_open_api_service_api.NeListOpenApiServiceApi()

    def tearDown(self):
        pass

    def test_query_ne_list(self):
        """
        Test case for query_ne_list

        查询列表信息
        """
        pass


if __name__ == '__main__':
    unittest.main()
