# coding: utf-8

"""
    AP IOT配置

    AP IOT配置北向接口，主要特性： · 查询AP IOT配置信息 · 配置AP IOT信息 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.iot_server1_dto import IotServer1Dto


class TestIotServer1Dto(unittest.TestCase):
    """ IotServer1Dto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIotServer1Dto(self):
        """
        Test IotServer1Dto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.iot_server1_dto.IotServer1Dto()
        pass


if __name__ == '__main__':
    unittest.main()
