# coding: utf-8

"""
    站点管理

    站点管理第三方接口。 场景：对站点增删改查操作的第三方接口。

    OpenAPI spec version: 1.3.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.create_site_dto import CreateSiteDto


class TestCreateSiteDto(unittest.TestCase):
    """ CreateSiteDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateSiteDto(self):
        """
        Test CreateSiteDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.create_site_dto.CreateSiteDto()
        pass


if __name__ == '__main__':
    unittest.main()
