# coding: utf-8

"""
    Portal在线用户查询

    查询Portal在线用户第三方北向接口。提供了Portal在线用户的查询、强制下线接口。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.portal_online_users_mgr_api import PortalOnlineUsersMgrApi


class TestPortalOnlineUsersMgrApi(unittest.TestCase):
    """ PortalOnlineUsersMgrApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.portal_online_users_mgr_api.PortalOnlineUsersMgrApi()

    def tearDown(self):
        pass

    def test_cut_portal_online_users(self):
        """
        Test case for cut_portal_online_users

        管理员强制Portal在线用户下线
        """
        pass

    def test_query_portal_online_user(self):
        """
        Test case for query_portal_online_user

        查询Portal在线用户
        """
        pass


if __name__ == '__main__':
    unittest.main()
