# coding: utf-8

"""
    交换机端口配置

    LSW端口配置北向接口，主要特性： · 查询交换机所有接口信息 · 修改交换机以太接口配置 · 创建交换机Eth-Trunk接口 · 修改交换机Eth-Trunk接口 · 删除交换机Eth-Trunk接口 

    OpenAPI spec version: 1.4.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.put_response_dto import PutResponseDto


class TestPutResponseDto(unittest.TestCase):
    """ PutResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutResponseDto(self):
        """
        Test PutResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.put_response_dto.PutResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
