# coding: utf-8

"""
    设备定时重启

    · 创建或修改定时重启、延时重启设备任务 · 查询重启设备任务的状态 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.reriod_reboot_device_param import ReriodRebootDeviceParam


class TestReriodRebootDeviceParam(unittest.TestCase):
    """ ReriodRebootDeviceParam unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReriodRebootDeviceParam(self):
        """
        Test ReriodRebootDeviceParam
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.reriod_reboot_device_param.ReriodRebootDeviceParam()
        pass


if __name__ == '__main__':
    unittest.main()
