# coding: utf-8

"""
    控制器支持第三方系统通过API接口获取用户上下线信息

    控制器支持第三方系统通过API接口获取用户上下线信息 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.authentication_log_detail_output_dto import AuthenticationLogDetailOutputDto


class TestAuthenticationLogDetailOutputDto(unittest.TestCase):
    """ AuthenticationLogDetailOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthenticationLogDetailOutputDto(self):
        """
        Test AuthenticationLogDetailOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.authentication_log_detail_output_dto.AuthenticationLogDetailOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
