# coding: utf-8

"""
    mac帐号管理

    mac帐号管理

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.mac_output_dto import MacOutputDto


class TestMacOutputDto(unittest.TestCase):
    """ MacOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMacOutputDto(self):
        """
        Test MacOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.mac_output_dto.MacOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
