# coding: utf-8

"""
    配置结果查询

    查询配置结果

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.feature_item_state_dto import FeatureItemStateDto


class TestFeatureItemStateDto(unittest.TestCase):
    """ FeatureItemStateDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeatureItemStateDto(self):
        """
        Test FeatureItemStateDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.feature_item_state_dto.FeatureItemStateDto()
        pass


if __name__ == '__main__':
    unittest.main()
