# coding: utf-8

"""
    上网时长流量策略

    上网时长流量策略编辑查询开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.delete_time_flow_fail_info import DeleteTimeFlowFailInfo


class TestDeleteTimeFlowFailInfo(unittest.TestCase):
    """ DeleteTimeFlowFailInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteTimeFlowFailInfo(self):
        """
        Test DeleteTimeFlowFailInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.delete_time_flow_fail_info.DeleteTimeFlowFailInfo()
        pass


if __name__ == '__main__':
    unittest.main()
