# coding: utf-8

"""
    时间模板管理

    时间模板第三方接口说明。 

    OpenAPI spec version: 1.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.day_content_dto import DayContentDto


class TestDayContentDto(unittest.TestCase):
    """ DayContentDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDayContentDto(self):
        """
        Test DayContentDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.day_content_dto.DayContentDto()
        pass


if __name__ == '__main__':
    unittest.main()
