# coding: utf-8

"""
    用户组管理

    用户组管理开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.update_usergroup_input_dto import UpdateUsergroupInputDto


class TestUpdateUsergroupInputDto(unittest.TestCase):
    """ UpdateUsergroupInputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateUsergroupInputDto(self):
        """
        Test UpdateUsergroupInputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.update_usergroup_input_dto.UpdateUsergroupInputDto()
        pass


if __name__ == '__main__':
    unittest.main()
