# coding: utf-8

"""
    终端用户管理

    终端用户管理开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.common_authorization_output_dto import CommonAuthorizationOutputDto


class TestCommonAuthorizationOutputDto(unittest.TestCase):
    """ CommonAuthorizationOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommonAuthorizationOutputDto(self):
        """
        Test CommonAuthorizationOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.common_authorization_output_dto.CommonAuthorizationOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
