# coding: utf-8

"""
    用户组管理

    用户组管理开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.usergroups_mgr_api import UsergroupsMgrApi


class TestUsergroupsMgrApi(unittest.TestCase):
    """ UsergroupsMgrApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.usergroups_mgr_api.UsergroupsMgrApi()

    def tearDown(self):
        pass

    def test_add_usergroup(self):
        """
        Test case for add_usergroup

        新增用户组
        """
        pass

    def test_del_usergroups(self):
        """
        Test case for del_usergroups

        删除用户组
        """
        pass

    def test_get_usergroups(self):
        """
        Test case for get_usergroups

        查询用户组
        """
        pass

    def test_update_usergroup(self):
        """
        Test case for update_usergroup

        修改用户组
        """
        pass


if __name__ == '__main__':
    unittest.main()
