# coding: utf-8

"""
    AP站点射频配置

    AP站点射频配置第三方接口说明。 

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.group_radio_config_api_dto import GroupRadioConfigApiDto


class TestGroupRadioConfigApiDto(unittest.TestCase):
    """ GroupRadioConfigApiDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupRadioConfigApiDto(self):
        """
        Test GroupRadioConfigApiDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.group_radio_config_api_dto.GroupRadioConfigApiDto()
        pass


if __name__ == '__main__':
    unittest.main()
