# coding: utf-8

"""
    交换机全局VLAN配置

    配置交换机全局VLAN 

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.lsw_global_vlan_del_resp_dto import LswGlobalVlanDelRespDto


class TestLswGlobalVlanDelRespDto(unittest.TestCase):
    """ LswGlobalVlanDelRespDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLswGlobalVlanDelRespDto(self):
        """
        Test LswGlobalVlanDelRespDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.lsw_global_vlan_del_resp_dto.LswGlobalVlanDelRespDto()
        pass


if __name__ == '__main__':
    unittest.main()
