# coding: utf-8

"""
    终端用户管理

    终端用户管理开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.third_user_info_data import ThirdUserInfoData


class TestThirdUserInfoData(unittest.TestCase):
    """ ThirdUserInfoData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testThirdUserInfoData(self):
        """
        Test ThirdUserInfoData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.third_user_info_data.ThirdUserInfoData()
        pass


if __name__ == '__main__':
    unittest.main()
