# coding: utf-8

"""
    防火墙设备NAT配置

    防火墙设备NAT配置第三方接口。

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.fw_nat_delete_response_fail_dto import FwNatDeleteResponseFailDto


class TestFwNatDeleteResponseFailDto(unittest.TestCase):
    """ FwNatDeleteResponseFailDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFwNatDeleteResponseFailDto(self):
        """
        Test FwNatDeleteResponseFailDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.fw_nat_delete_response_fail_dto.FwNatDeleteResponseFailDto()
        pass


if __name__ == '__main__':
    unittest.main()
