# coding: utf-8

"""
    网络设备管理

    提供北向查询网络设备服务。 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ne_detail_info import NeDetailInfo


class TestNeDetailInfo(unittest.TestCase):
    """ NeDetailInfo unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNeDetailInfo(self):
        """
        Test NeDetailInfo
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ne_detail_info.NeDetailInfo()
        pass


if __name__ == '__main__':
    unittest.main()
