# coding: utf-8

"""
    实体资源北向接口

    实体资源条件查询。 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.north_entity_res_service_api import NorthEntityResServiceApi


class TestNorthEntityResServiceApi(unittest.TestCase):
    """ NorthEntityResServiceApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.north_entity_res_service_api.NorthEntityResServiceApi()

    def tearDown(self):
        pass

    def test_get_frame_list(self):
        """
        Test case for get_frame_list

        条件查询机框资源
        """
        pass

    def test_get_ot_point_list(self):
        """
        Test case for get_ot_point_list

        条件查询光口资源
        """
        pass

    def test_get_port_list(self):
        """
        Test case for get_port_list

        条件查询端口资源
        """
        pass

    def test_get_slot_list(self):
        """
        Test case for get_slot_list

        条件查询单板资源
        """
        pass

    def test_get_sub_slot_list(self):
        """
        Test case for get_sub_slot_list

        条件查询子卡资源
        """
        pass


if __name__ == '__main__':
    unittest.main()
