# coding: utf-8

"""
    AP DHCP配置

    AP DHCP配置第三方接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ip_binding_mac_config_api_dto import IpBindingMacConfigApiDto


class TestIpBindingMacConfigApiDto(unittest.TestCase):
    """ IpBindingMacConfigApiDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIpBindingMacConfigApiDto(self):
        """
        Test IpBindingMacConfigApiDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ip_binding_mac_config_api_dto.IpBindingMacConfigApiDto()
        pass


if __name__ == '__main__':
    unittest.main()
