# coding: utf-8

"""
    实体资源北向接口

    实体资源条件查询。 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.slot_res_data import SlotResData


class TestSlotResData(unittest.TestCase):
    """ SlotResData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSlotResData(self):
        """
        Test SlotResData
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.slot_res_data.SlotResData()
        pass


if __name__ == '__main__':
    unittest.main()
