# coding: utf-8

"""
    防火墙设备NAT配置

    防火墙设备NAT配置第三方接口。

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.get_fw_nat_response_dto import GetFwNatResponseDto


class TestGetFwNatResponseDto(unittest.TestCase):
    """ GetFwNatResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetFwNatResponseDto(self):
        """
        Test GetFwNatResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.get_fw_nat_response_dto.GetFwNatResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
