# coding: utf-8

"""
    mac帐号管理

    mac帐号管理

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.mac_account_api import MacAccountApi


class TestMacAccountApi(unittest.TestCase):
    """ MacAccountApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.mac_account_api.MacAccountApi()

    def tearDown(self):
        pass

    def test_create_mac_account(self):
        """
        Test case for create_mac_account

        创建mac账号
        """
        pass

    def test_delete_mac_account(self):
        """
        Test case for delete_mac_account

        删除mac帐号
        """
        pass

    def test_get_mac_account_list(self):
        """
        Test case for get_mac_account_list

        查询mac帐号
        """
        pass

    def test_update_mac_account(self):
        """
        Test case for update_mac_account

        修改mac帐号
        """
        pass


if __name__ == '__main__':
    unittest.main()
