# coding: utf-8

"""
    CIS服务接口

    CIS操作接口说明： 1、创建CIS隔离 2、创建CIS阻断 3、撤销CIS阻断/隔离 4、阻断隔离应用状态查询 5、CIS策略命中率查询 

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.partition_policy_api import PartitionPolicyApi


class TestPartitionPolicyApi(unittest.TestCase):
    """ PartitionPolicyApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.partition_policy_api.PartitionPolicyApi()

    def tearDown(self):
        pass

    def test_delete_threat_defense(self):
        """
        Test case for delete_threat_defense

        撤销CIS阻断/隔离
        """
        pass

    def test_interdiction(self):
        """
        Test case for interdiction

        创建CIS阻断策略
        """
        pass

    def test_isolate_vm(self):
        """
        Test case for isolate_vm

        创建CIS隔离策略
        """
        pass

    def test_query_hits(self):
        """
        Test case for query_hits

        CIS策略命中率查询
        """
        pass

    def test_query_status(self):
        """
        Test case for query_status

        查询阻断/隔离应用状态
        """
        pass


if __name__ == '__main__':
    unittest.main()
