# coding: utf-8

"""
    交换机有线认证模板配置

    交换机有线认证模板，主要包括： · 创建站点下交换机有线认证模板配置 · 查询站点下交换机有线认证模板配置 · 修改站点下交换机有线认证模板配置 · 删除站点下交换机有线认证模板配置 · 修改站点交换机有线认证部分模板配置 · 增量绑站点交换机有线认证模板配置定 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.apis.lswauth_api import LswauthApi


class TestLswauthApi(unittest.TestCase):
    """ LswauthApi unit test stubs """

    def setUp(self):
        self.api = cloudcampus.apis.lswauth_api.LswauthApi()

    def tearDown(self):
        pass

    def test_create_lsw_auth(self):
        """
        Test case for create_lsw_auth

        创建站点下交换机有线认证模板配置
        """
        pass

    def test_delete_lsw_auth(self):
        """
        Test case for delete_lsw_auth

        删除站点下交换机有线认证模板配置
        """
        pass

    def test_get_lsw_auth(self):
        """
        Test case for get_lsw_auth

        查询站点下交换机有线认证模板配置
        """
        pass

    def test_update_lsw_auth(self):
        """
        Test case for update_lsw_auth

        修改站点下交换机有线认证模板配置
        """
        pass

    def test_update_lsw_auth_inc(self):
        """
        Test case for update_lsw_auth_inc

        增量绑定交换机无线认证模板配置
        """
        pass

    def test_update_lsw_auth_pro_inc(self):
        """
        Test case for update_lsw_auth_pro_inc

        修改站点交换机有线认证部分模板配置
        """
        pass


if __name__ == '__main__':
    unittest.main()
