# coding: utf-8

"""
    配置结果查询

    查询配置结果

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.batch_get_dto import BatchGetDto


class TestBatchGetDto(unittest.TestCase):
    """ BatchGetDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBatchGetDto(self):
        """
        Test BatchGetDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.batch_get_dto.BatchGetDto()
        pass


if __name__ == '__main__':
    unittest.main()
