# coding: utf-8

"""
    设备出厂设置恢复

    设备恢复出厂设置第三方接口。

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.reset_device_response import ResetDeviceResponse


class TestResetDeviceResponse(unittest.TestCase):
    """ ResetDeviceResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResetDeviceResponse(self):
        """
        Test ResetDeviceResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.reset_device_response.ResetDeviceResponse()
        pass


if __name__ == '__main__':
    unittest.main()
