# coding: utf-8

"""
    交换机STP保护配置

    主要特性： · 创建交换机STP保护配置 · 修改交换机STP保护配置 · 查询交换机STP保护配置 · 删除交换机STP保护配置 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.response_base_dto import ResponseBaseDto


class TestResponseBaseDto(unittest.TestCase):
    """ ResponseBaseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseBaseDto(self):
        """
        Test ResponseBaseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.response_base_dto.ResponseBaseDto()
        pass


if __name__ == '__main__':
    unittest.main()
