# coding: utf-8

"""
    RADIUS模板管理

    RADIUS模板配置第三方北向接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.radius_temp_dto_slave_auth_server import RadiusTempDtoSlaveAuthServer


class TestRadiusTempDtoSlaveAuthServer(unittest.TestCase):
    """ RadiusTempDtoSlaveAuthServer unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRadiusTempDtoSlaveAuthServer(self):
        """
        Test RadiusTempDtoSlaveAuthServer
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.radius_temp_dto_slave_auth_server.RadiusTempDtoSlaveAuthServer()
        pass


if __name__ == '__main__':
    unittest.main()
