# coding: utf-8

"""
    租户管理

    租户管理第三方北向接口。 · 提供租户创建接口 · 提供租户删除接口 · 提供租户查询接口 

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.tenant_list_dto import TenantListDto


class TestTenantListDto(unittest.TestCase):
    """ TenantListDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTenantListDto(self):
        """
        Test TenantListDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.tenant_list_dto.TenantListDto()
        pass


if __name__ == '__main__':
    unittest.main()
