# coding: utf-8

"""
    AP站点模板射频配置

    AP站点模板射频配置第三方接口说明。 

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.group_radio2g_config_dto import GroupRadio2gConfigDto


class TestGroupRadio2gConfigDto(unittest.TestCase):
    """ GroupRadio2gConfigDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupRadio2gConfigDto(self):
        """
        Test GroupRadio2gConfigDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.group_radio2g_config_dto.GroupRadio2gConfigDto()
        pass


if __name__ == '__main__':
    unittest.main()
