# coding: utf-8

"""
    RADIUS模板管理

    RADIUS模板配置第三方北向接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.create_radius_temp_response_dto import CreateRadiusTempResponseDto


class TestCreateRadiusTempResponseDto(unittest.TestCase):
    """ CreateRadiusTempResponseDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateRadiusTempResponseDto(self):
        """
        Test CreateRadiusTempResponseDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.create_radius_temp_response_dto.CreateRadiusTempResponseDto()
        pass


if __name__ == '__main__':
    unittest.main()
