# coding: utf-8

"""
    路由器设备静态路由配置

    路由器设备静态路由配置第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.failed_oper_dto import FailedOperDto


class TestFailedOperDto(unittest.TestCase):
    """ FailedOperDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFailedOperDto(self):
        """
        Test FailedOperDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.failed_oper_dto.FailedOperDto()
        pass


if __name__ == '__main__':
    unittest.main()
