# coding: utf-8

"""
    ACL模板管理

    ACL模板第三方管理接口说明。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.acl_dto_detail import AclDtoDetail


class TestAclDtoDetail(unittest.TestCase):
    """ AclDtoDetail unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAclDtoDetail(self):
        """
        Test AclDtoDetail
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.acl_dto_detail.AclDtoDetail()
        pass


if __name__ == '__main__':
    unittest.main()
