# coding: utf-8

"""
    mac帐号管理

    mac帐号管理

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.mac_data_list import MacDataList


class TestMacDataList(unittest.TestCase):
    """ MacDataList unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMacDataList(self):
        """
        Test MacDataList
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.mac_data_list.MacDataList()
        pass


if __name__ == '__main__':
    unittest.main()
