# coding: utf-8

"""
    设备基本信息管理

    设备相关操作接口。 场景：对设备增删改查操作的第三方接口。

    OpenAPI spec version: 1.6.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.modify_device_bean import ModifyDeviceBean


class TestModifyDeviceBean(unittest.TestCase):
    """ ModifyDeviceBean unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifyDeviceBean(self):
        """
        Test ModifyDeviceBean
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.modify_device_bean.ModifyDeviceBean()
        pass


if __name__ == '__main__':
    unittest.main()
