# coding: utf-8

"""
    路由器设备静态路由配置

    路由器设备静态路由配置第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.ar_staticroute_delete_response_fail_dto import ArStaticrouteDeleteResponseFailDto


class TestArStaticrouteDeleteResponseFailDto(unittest.TestCase):
    """ ArStaticrouteDeleteResponseFailDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArStaticrouteDeleteResponseFailDto(self):
        """
        Test ArStaticrouteDeleteResponseFailDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.ar_staticroute_delete_response_fail_dto.ArStaticrouteDeleteResponseFailDto()
        pass


if __name__ == '__main__':
    unittest.main()
