# coding: utf-8

"""
    上网时长流量策略

    上网时长流量策略编辑查询开放API。 

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.time_flow_config_output_dto import TimeFlowConfigOutputDto


class TestTimeFlowConfigOutputDto(unittest.TestCase):
    """ TimeFlowConfigOutputDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeFlowConfigOutputDto(self):
        """
        Test TimeFlowConfigOutputDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.time_flow_config_output_dto.TimeFlowConfigOutputDto()
        pass


if __name__ == '__main__':
    unittest.main()
