# coding: utf-8

"""
    框式交换机板卡信息操作

    框式上云相关操作接口： 场景：对框式交换机信息查询操作的第三方接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.fan_info_dto import FanInfoDto


class TestFanInfoDto(unittest.TestCase):
    """ FanInfoDto unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFanInfoDto(self):
        """
        Test FanInfoDto
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.fan_info_dto.FanInfoDto()
        pass


if __name__ == '__main__':
    unittest.main()
