# coding: utf-8

"""
    TACACS配置

    TACACS配置北向接口，主要特性： · 配置TACACS · 查询TACACS 

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cloudcampus
from cloudcampus.rest import ApiException
from cloudcampus.models.edit_tacacs_config_response import EditTacacsConfigResponse


class TestEditTacacsConfigResponse(unittest.TestCase):
    """ EditTacacsConfigResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditTacacsConfigResponse(self):
        """
        Test EditTacacsConfigResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cloudcampus.models.edit_tacacs_config_response.EditTacacsConfigResponse()
        pass


if __name__ == '__main__':
    unittest.main()
