# coding: utf-8

"""

    提供cloudcampus北向接口。

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = "cloudcampusPythonSdk"
VERSION = "V300R019C00"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name="cloudcampusPythonSdk",
    version="V300R019C00",
    description="cloudcampusPythonSdk",
    author_email="",
    url="",
    keywords=["Swagger", "cloudcampus"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    提供cloudcampus北向api服务。 
    """
)
